input {
  beats {
    port => 5044
  }
}
filter {
  translate {
    field => "[winlog][event_id]"
    destination => "[@metadata][target_table]"
    dictionary => {
      "4624" => "AuthenticationEvents"
      "4625" => "AuthenticationEvents"
      "4634" => "AuthenticationEvents"
      "4648" => "AuthenticationEvents"
      "4688" => "ProcessEvents"
      "1"    => "ProcessEvents"
      "4720" => "AccountManagementEvents"
      "4722" => "AccountManagementEvents"
      "4725" => "AccountManagementEvents"
      "4732" => "AccountManagementEvents"
      "4738" => "AccountManagementEvents"
      "7045" => "ServiceEvents"
      "4697" => "ServiceEvents"
    }
  }
  if "_translate_failure" in [tags] {
    drop {}
  }
  if [@metadata][target_table] == "AuthenticationEvents" {
    mutate {
      convert => { "[winlog][event_data][LogonType]" => "integer" }
      rename => {
        "[winlog][event_data][SubjectUserName]" => "[user][name]"
        "[winlog][event_data][SubjectDomainName]" => "[user][domain]"
        "[winlog][event_data][IpAddress]" => "[source][ip]"
        "[winlog][event_data][LogonType]" => "[winlog][logon_type]"
      }
    }
    geoip {
      source => "[source][ip]"
      target => "[source][geo]"
    }
  }
  else if [@metadata][target_table] == "ProcessEvents" {
    mutate {
      rename => {"[winlog][event_data][SubjectUserName]" => "[user][name]" }
      rename => {"[winlog][event_data][User]" => "[user][name]" }
      }
    }
  if [@metadata][target_table] {
    mutate { add_field => { "[@metadata][ingestion_mapping]" => "%{[@metadata][target_table]}_Mapping" }
    }
  }
}
output {
  stdout { codec => rubydebug }
  azure_event_hubs {
    time_to_flush => 20
    service_namespace => "${EVENTHUB_NAMESPACE}"
    event_hub => "${EVENTHUB_NAME}"
    sas_key_name => "${EVENTHUB_SAS_KEY_NAME}"
    sas_key => "${EVENTHUB_SAS_KEY}"
    properties_bag => {
      "Table" => "%{[@metadata][target_table]}"
      "Format" => "json"
      "IngestionMappingReference" => "%{[@metadata][ingestion_mapping]}"
    }
    codec => "json_lines"
  }
}
